version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - FPM_RUN_USER=${FPM_RUN_USER}
      - FPM_RUN_GROUP=${FPM_RUN_GROUP}
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    ports:
      - ${APP_FPM_ADDR}:9000
