version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - FPM_RUN_USER=${FPM_RUN_USER}
      - FPM_RUN_GROUP=${FPM_RUN_GROUP}
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    networks:
      self:
        ipv4_address: ${NETWORK_APP_IP}

networks:
  self:
    driver: bridge
    ipam:
      config:
      - subnet: ${NETWORK_SUBNET}
